# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you dont use vgo
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64