# =============================================
# THIS FILE SHOULD NOT BE PACKED INTO BINARY!!
# =============================================
#
# gf pack config packed/config.go -n=packed
#
# Compile cli itself.
[gfcli]
    [gfcli.build]
        name     = "gf"
        arch     = "all"
        system   = "all"
        mod      = "none"
        cgo      = 0
        # mod     = "none"
        # version = "v1.0.0"
        # output  = "./bin"
        # extra   = ""
