package consts

const TemplateModelForDaoIndexContent = `
// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

{TplPackageImports}

{TplModelStructs}
`

const TemplateModelForDaoStructContent = `
// {TplTableNameCamelCase}ForDao is the golang structure of table {TplTableName} for DAO operations like Where/Data.
{TplStructDefine}
`
