package consts

const TemplateDaoModelIndexContent = `
// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

{TplPackageImports}

{TplModelStructs}
`

const TemplateDaoModelStructContent = `
// {TplTableNameCamelCase} is the golang structure for table {TplTableName}.
{TplStructDefine}
`
